# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'HttpCacheApp' do
  pod 'AFNetworking'
  pod 'SDWebImage', '~>3.6'
end

target 'HttpCacheAppTests' do

end

